name: arroyoseco
favicon: null
layout_spectrum: 0.8102647091727704
typography_spectrum: 0.1375517959240824
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#271610'
    - '#60636a'
    - '#faf6ed'
    - '#d1cdc2'
    - '#91897c'
  brandStrength: 0.3125
  lightness: 0.9114696043543518
  saturation: 0.8096860824152827
  rhythmicContrast: 0.7293004731182009
purpose: []
